name: Code quality

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Biome Version
        run: ./scripts/check-biome-version.sh
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "1.9.4"
      - name: Run Biome
        run: biome ci .
